name: Deploy Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: sbp_7d2cff54fb70b0f842367526b088aaf714405f90
      PROJECT_ID: uiyzrgekobuqgfvoipow

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase functions deploy --project-ref uiyzrgekobuqgfvoipow 